#!/bin/bash

GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

CURR_DIR=`pwd`
LINE_BREAK="============================================================"
DONE="$LINE_BREAK\n${GREEN}Done${NC}\n\n"

echo
echo "${CYAN}Updating git repositories...${NC}\n$LINE_BREAK"
cd "/Users/donovanmoini/code"
./scripts/update_git_repos
cd $pwd
echo "$DONE"

echo "${CYAN}Upgrading Homebrew...${NC}\n$LINE_BREAK"
brew upgrade
echo "$DONE"

echo "${CYAN}Upgrading npm...${NC}\n$LINE_BREAK"
npm i -g npm
echo "$DONE"

echo "${CYAN}Upgrading outdated global npm packages...${NC}\n$LINE_BREAK"
npm outdated -g --depth=0
echo
npm update -g
echo "$DONE"

echo "${CYAN}Upgrading oh-my-zsh...${NC}\n$LINE_BREAK"
env ZSH=$ZSH sh $ZSH/tools/upgrade.sh
echo "$DONE"

echo "${CYAN}Upgrading pip...${NC}\n$LINE_BREAK"
pip install --upgrade pip
echo "$DONE"
