#!/bin/bash

CURR_DIR=`pwd`
CODE_DIR="$HOME/code"
REPO_TOPIC=`echo $*`

OLD_IFS="$IFS"
IFS="-"
HYPHENATED_REPO_TOPIC="$*"
IFS=$OLD_IFS
REPO_URL=`echo ${HYPHENATED_REPO_TOPIC}-practice | tr '[:upper:]' '[:lower:]'`

if [ -z $1 ]
then
    echo "How to run script: create_practice_git_repo <topic>"
    exit 1
fi

cd $CODE_DIR
mkdir $REPO_URL
cd $REPO_URL
touch README.md
echo "# $REPO_TOPIC Practice
Practice projects to learn $REPO_TOPIC." >> README.md

git init
git add . && git commit -m "Created $REPO_TOPIC practice repository."
hub create -p -d "Practice projects to learn $REPO_TOPIC."
git push --set-upstream origin master

cd $CURR_DIR