#!/bin/bash

GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

COPYING_ECHO() {
    echo -e "${NC}Copying $1...${NC}"
}

COPYING_ECHO "bash files"
cp ~/.bash_profile ~/code/dot-files-and-scripts/bash/
cp ~/.bashrc ~/code/dot-files-and-scripts/bash/

COPYING_ECHO "git config"
cp ~/.gitconfig ~/code/dot-files-and-scripts/git/

COPYING_ECHO "homebrew packages"
brew bundle dump
mv Brewfile /Users/donovanmoini/code/dot-files-and-scripts/homebrew/

COPYING_ECHO "pip packages"
pip freeze >> pip-packages.txt
mv pip-packages.txt ~/code/dot-files-and-scripts/pip/

COPYING_ECHO "script files"
cp -r ~/code/scripts ~/code/dot-files-and-scripts/

COPYING_ECHO "vim files"
cp ~/.vimrc ~/code/dot-files-and-scripts/vim/
rsync -av --progress ~/.vim ~/code/dot-files-and-scripts/vim/ --exclude .git --exclude .DS_Store &> /dev/null

COPYING_ECHO "zsh files"
cp ~/.zshrc ~/code/dot-files-and-scripts/zsh/
