#!/bin/sh

GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

CURR_DIR=`pwd`
LINE_BREAK="============================================================"
DONE="$LINE_BREAK\n${GREEN}Done${NC}\n\n"

echo
echo "${CYAN}Copying over bash files...${NC}\n$LINE_BREAK"
cp ~/.bash_profile ~/code/dot-files-and-scripts/bash
echo "$DONE"

echo
echo "${CYAN}Copying over script files...${NC}\n$LINE_BREAK"
cp -r ~/code/scripts ~/code/dot-files-and-scripts/
echo "$DONE"

echo
echo "${CYAN}Copying over vim files...${NC}\n$LINE_BREAK"
cp ~/.vimrc ~/code/dot-files-and-scripts/vim
rsync -av --progress ~/.vim ~/code/dot-files-and-scripts/vim --exclude .git --exclude .DS_Storecd $CURR_DIR
echo "$DONE"

echo
echo "${CYAN}Copying over zsh files...${NC}\n$LINE_BREAK"
cp ~/.zshrc ~/code/dot-files-and-scripts/zsh
echo "$DONE"