#!/bin/bash

source ~/.functions

CYAN='\033[0;96m'
NC='\033[0m'
CURR_DIR=$(pwd)

updateEcho() {
    echo -e "${CYAN}Updating $1...${NC}"
}

isNotInstalled() {
    for cmd in "$@"; do
        if ! which "$cmd" &>/dev/null; then
            echo -e "$cmd is not installed\n"
            return 0
        fi
    done
    return 1
}

updateHomebrew() {
    if isNotInstalled "brew"; then return; fi

    updateEcho "Homebrew"
    brew update
    brew upgrade
    brew cleanup -s
    echo

    updateEcho "Homebrew Casks"
    brew cask outdated
    brew cask upgrade
    brew cleanup -s
    echo
}

updateMas() {
    if isNotInstalled "mas"; then return; fi

    updateEcho "App Store Applications"
    mas outdated
    mas upgrade
    echo
}

updateDotfiles() {
    if isNotInstalled "git"; then return; fi

    updateEcho "Dotfiles"
    update_dotfiles
    echo
}

updateLocalGitHubRepositories() {
    if isNotInstalled "git" "hub"; then return; fi

    updateEcho "GitHub Repositories"
    update_git_repos
}

updateMacOS() {
    updateEcho "macOS"
    softwareupdate -i -a
    echo
}

updateNPM() {
    if isNotInstalled "npm"; then return; fi

    updateEcho "NPM Packages"
    outdated_npm_packages=$(npm outdated -g --depth=0)
    if [ -z "$outdated_npm_packages" ]; then
        echo "Global npm packages are up to date"
    else
        echo "$outdated_npm_packages"
        echo
        npm update -g
    fi
    echo
}

updatePip() {
    if isNotInstalled "pip"; then return; fi

    updateEcho "Pip"
    syspip install --upgrade pip
    echo

    updateEcho "Pip Packages"
    outdated_pip_packages=$(syspip list --outdated)
    if [ -z "$outdated_pip_packages" ]; then
        echo "Global pip packages are up to date"
    else
        echo "$outdated_pip_packages"
        echo
        syspip install --upgrade $(syspip list --outdated 2>/dev/null | sed 1,2d | awk '{printf $1 " " }' | sed 's/\ $//')
    fi
    echo
}

updateOhMyZsh() {
    if ! [[ -d $HOME/.oh-my-zsh ]]; then
        echo -e "Oh My Zsh is not installed\n";
        return;
    fi

    updateEcho "Oh My Zsh"
    env ZSH=$ZSH sh $ZSH/tools/upgrade.sh
}

updateAll() {
    updateHomebrew
    updateMas
    updateDotfiles
    updateLocalGitHubRepositories
    updateMacOS
    updateNPM
    updatePip
    updateOhMyZsh
    nyan
}

updateAll
