#!/bin/bash

source ~/.functions

DOTFILES_DIR="${HOME}/code/dotfiles"
VSCODE_DIR="${HOME}/Library/Application Support/Code/User"

GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

updateEcho() {
    echo -e "${NC}Updating $1 files${NC}"
}

updateGit() {
    updateEcho "Git"
    cp "${HOME}/.gitconfig" "${DOTFILES_DIR}/git"
}

updateHomebrew() {
    updateEcho "Homebrew"
    # If Brewfile already exists, delete it and create new one
    if [ -f Brewfile ]; then rm Brewfile; fi
    
    brew bundle dump
    mv Brewfile "${DOTFILES_DIR}/homebrew"
}

updateNPM() {
    updateEcho "NPM"
    # To import these packages, run `cat npm-global-packages.txt | xargs npm i -g`
    npm list -g --parseable --depth=0 | sed '1d' | awk '{gsub(/\/.*\//,"",$1); print}' > npm-global-packages.txt
    mv npm-global-packages.txt "${DOTFILES_DIR}/npm"
}

updatePip() {
    updateEcho "Pip"
    syspip freeze > pip-packages.txt
    mv pip-packages.txt "${DOTFILES_DIR}/pip"
}

updateScripts() {
    updateEcho "script"
    cp -r "${HOME}/code/scripts" "${DOTFILES_DIR}"
}

updateShell() {
    updateEcho "shell"
    cp "${HOME}/.aliases" "${DOTFILES_DIR}/shell"
    cp "${HOME}/.exports" "${DOTFILES_DIR}/shell"
    cp "${HOME}/.functions" "${DOTFILES_DIR}/shell"
}

updateVim() {
    updateEcho "Vim"
    cp "${HOME}/.vimrc" "${DOTFILES_DIR}/vim"
    rsync -av --progress "${HOME}/.vim" "${DOTFILES_DIR}/vim" --exclude .git --exclude .DS_Store --exclude .netrwhist &>/dev/null
}

updateVSCode() {
    updateEcho "VS Code"
    cp "${VSCODE_DIR}/settings.json" "${DOTFILES_DIR}/vscode"
    cp "${VSCODE_DIR}/keybindings.json" "${DOTFILES_DIR}/vscode"
}

updateZsh() {
    updateEcho "Zsh"
    cp "${HOME}/.zshrc" "${DOTFILES_DIR}/zsh/"
}

updateAll() {
    updateGit
    updateHomebrew
    updateNPM
    updatePip
    updateScripts
    updateShell
    updateVim
    updateVSCode
    updateZsh
}

updateAll
