#!/bin/bash

source ~/.functions

GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'
CURR_DIR=$(pwd)

UPDATING_ECHO() {
    echo -e "${CYAN}Updating $1...${NC}"
}

UPDATING_ECHO "appstore apps"
mas upgrade
echo

UPDATING_ECHO "dotfiles"
update_dotfiles
echo

UPDATING_ECHO "git repositories"
cd "${HOME}/code"
update_git_repos
cd $CURR_DIR
echo

UPDATING_ECHO "Homebrew"
brew update
brew upgrade
brew cask upgrade
brew cleanup
echo

UPDATING_ECHO "macOS"
softwareupdate -i -a
echo

UPDATING_ECHO "npm packages"
outdated_npm_packages=$(npm outdated -g --depth=0)
if [ -z "$outdated_npm_packages" ]; then
    echo "Global npm packages are up to date."
else
    echo "$outdated_npm_packages"
    echo
    npm update -g
fi
echo

UPDATING_ECHO "pip and pip packages"
syspip install --upgrade pip
echo
outdated_pip_packages=$(syspip list --outdated)
if [ -z "$outdated_pip_packages" ]; then
    echo "Global pip packages are up to date."
else
    echo "$outdated_pip_packages"
    echo
    syspip install --upgrade $(syspip list --outdated 2> /dev/null | sed 1,2d | awk '{printf $1 " " }' | sed 's/\ $//')
fi
echo

UPDATING_ECHO "zsh"
env ZSH=$ZSH sh $ZSH/tools/upgrade.sh

nyan
