#!/bin/sh

GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

CURR_DIR=`pwd`
DONE="${GREEN}Done${NC}\n"
COPYING_ECHO() {
    echo "${CYAN}Copying $1...${NC}"
}

COPYING_ECHO "bash files"
cp ~/.bash_profile ~/code/dot-files-and-scripts/bash
cp ~/.bashrc ~/code/dot-files-and-scripts/bash
echo "$DONE"

COPYING_ECHO "script files"
cp -r ~/code/scripts ~/code/dot-files-and-scripts/
echo "$DONE"

COPYING_ECHO "vim files"
cp ~/.vimrc ~/code/dot-files-and-scripts/vim
rsync -av --progress ~/.vim ~/code/dot-files-and-scripts/vim --exclude .git --exclude .DS_Store
echo "$DONE"

COPYING_ECHO "zsh files"
cp ~/.zshrc ~/code/dot-files-and-scripts/zsh
echo "$DONE"
