#!/bin/sh

GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

CURR_DIR=`pwd`
LINE_BREAK="============================================================"
DONE="$LINE_BREAK\n${GREEN}Done${NC}\n\n"
UPDATING_ECHO() {
    echo "${CYAN}Updating $1...${NC}\n$LINE_BREAK"
}

echo
UPDATING_ECHO "git repositories"
cd "/Users/donovanmoini/code"
./scripts/update_git_repos
cd $CURR_DIR
echo "$DONE"

UPDATING_ECHO "Homebrew"
brew upgrade
echo "$DONE"

UPDATING_ECHO "outdated global npm packages"
npm outdated -g --depth=0
echo
npm update -g
echo "$DONE"

UPDATING_ECHO "oh-my-zsh"
env ZSH=$ZSH sh $ZSH/tools/upgrade.sh
echo "$DONE"

UPDATING_ECHO "pip"
pip install --upgrade pip
echo "$DONE"
